Updated scripts to work with Mac environments

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,59 +1,115 @@
 #! /bin/bash
 
+
 COLOR='\e[0;32m'
+STATUS_COLOR='\e[0;32m'
+ERROR_COLOR='\e[0;31m'
 NC='\e[0m'
 
-folder_mongo_root=`sudo find / -name mongod | sed 's/.\{11\}$//'`
+echo_Status () {
+	echo -e "${STATUS_COLOR}${1}${NC}"
+}
 
-###### CHECK/EXECUTE MONGOD
-echo -e "${COLOR}Checking for running instance of Mongo DB server.${NC}"
-mongod_running=`pgrep -f mongod | wc -l`
-if [[ $mongod_running == 0 ]]
-then  	echo -e "${COLOR}Mongo DB server is not running${NC}"
-	echo -e "${COLOR}Starting Mongo DB server${NC}"
-	sudo ${folder_mongo_root}/bin/mongod --fork --logpath ${folder_mongo_root}/server.log
-else	echo -e "${COLOR}Running instance of Mongo DB server detected.${NC}"
-	echo -e "${COLOR}Proceeding with execution...${NC}"
+echo_Error () {
+	echo -e "${ERROR_COLOR}${1}${NC}"
+}
+
+######INITIALIZATION CODE = Derive/validate paths.
+folder_crisisServer_root=`pwd`
+folder_mongo_root=`sudo which mongod`
+if [ "${folder_mongo_root}" = "" ] #Check mongod was found
+then
+	echo_Error"Could not find location of mongod"
+	exit 1
+else
+	folder_mongo_root=${folder_mongo_root%\/mongod}
+	if [ ! -e ${folder_crisisServer_root}/crisisServer.py ]
+	then
+		echo_Error "Could not find location of crisisServer.py"
+	exit 1
+	fi	
 fi
 
+######INITIALIZATION CODE ends
 
-##### DROP CURRENT_DATABASE IN MONGO DB
-echo -e "${COLOR}Inspecting Database for \"Current Database\" collection${NC}"
+
+
+###### CHECK/EXECUTE MONGOD
+echo_Status "Checking for running instance of Mongo DB server."
+mongod_running=`pgrep -f mongod | wc -l`
+if [[ $mongod_running == 0 ]]
+then  	echo_Status "Mongo DB server is not running"
+	echo_Status "Starting Mongo DB server"
+	sudo ${folder_mongo_root}/mongod --fork --logpath ${folder_mongo_root}/mongo_server.log
+
+	###Validate mongod has begun execution
+	mongod_running=`pgrep -f mongod | wc -l`
+	if [[ $mongod_running == 0 ]]
+	then 	echo_Error "Failed to start Mongo DB server. Check ${folder_mongo_root}/mongo_server.log for details"
+		exit 2
+	fi
+
+#skip 		
+else	echo_Status "Running instance of Mongo DB server detected."
+	echo_Status "Proceeding with execution..."
+fi
+###### CHECK/EXECUTE MONGOD ends
+
+###### DROP CURRENT_DATABASE IN MONGO DB
+echo_Status "Inspecting Database for \"Current Database\" collection"
 mongo << EOF
 use current_database
 db.dropDatabase()
 exit
 EOF
 
-echo -e "${COLOR}Current Database wiped for new execution.${NC}"
-
+echo_Status "Current Database wiped for new execution."
+###### DROP CURRENT_DATABASE IN MONGO DB ends
 
 ##### STARTING crisisServer.py
-echo -e "${COLOR}Checking for running instance of crisisSever${NC}"
+echo_Status "Checking for running instance of crisisSever"
 crisisServer_running=`pgrep -f crisisServer.py | wc -l`
 if [[ $crisisServer_running == 0 ]]
-then  	echo -e "${COLOR}crisisServer is not running${NC}"
-	echo -e "${COLOR}Starting crisisServer${NC}"
-else	echo -e "${COLOR}Running instance of crisisServer detected.${NC}"
-	echo -e "${COLOR}Killing existing instance and rerunning server${NC}"
+then  	echo_Status "crisisServer is not running"
+	echo_Status "Starting crisisServer"
+
+#reset
+else	echo_Status "Running instance of crisisServer detected."
+	echo_Status "Killing existing instance and rerunning server"
 	pgrep -f crisisServer.py | xargs kill
 fi
-#nohup python ${folder_crisisServer_root}/crisisServer.py &
-nohup python crisisServer.py &
+nohup python ${folder_crisisServer_root}/crisisServer.py &
 sleep 1
-echo -e "${COLOR}CrisisServer initiated.${NC}"
 
-##### STARTING historicalTweets.py
-echo -e "${COLOR}Checking for running instance of historicalTweets.py${NC}"
+###Validate crisisServer has begun execution
+crisisServer_running=`pgrep -f crisisServer.py | wc -l`
+if [[ $crisisServer_running == 0 ]]
+then 	echo_Error "Could not start crisisServer.py"
+	exit 3
+fi
+echo_Status "CrisisServer initiated."
+###### STARTING crisisServer.py ends
+
+###### STARTING historicalTweets.py
+echo_Status "Checking for running instance of historicalTweets.py"
 historicalTweets_running=`pgrep -f historicalTweets.py | wc -l`
 if [[ $historicalTweets_running == 0 ]]
-then  	echo -e "${COLOR}historicalTweets.py is not running${NC}"
-	echo -e "${COLOR}Starting historical Tweets pull${NC}"
-else	echo -e "${COLOR}Running instance of historicalTweets.py detected.${NC}"
-	echo -e "${COLOR}Killing existing instance and re-executing${NC}"
+then  	echo_Status "historicalTweets.py is not running"
+	echo_Status "Starting historical Tweets pull"
+
+#reset
+else	echo_Status "Running instance of historicalTweets.py detected."
+	echo_Status "Killing existing instance and re-executing"
 	pgrep -f historicalTweets.py | xargs kill
 fi
-nohup python historicalTweets.py &
-#nohup python ${folder_crisisServer_root}/historicalTweets.py &
+nohup python ${folder_crisisServer_root}/historicalTweets.py &
 sleep 1
-echo -e "${COLOR}Historical Tweets are now being pulled.${NC}"
+
+###Validate historicalTweets has begun execution
+historicalTweets_running=`pgrep -f historicalTweets.py | wc -l`
+if [[ $historicalTweets_running == 0 ]]
+then 	echo_Status "Could not start historicaltweeets.py"
+	exit 4
+fi
+echo_Status "Historical Tweets are now being pulled."
+###### STARTIN historicalTweets.py ends
diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,43 +1,71 @@
 #! /bin/bash
 
 COLOR='\e[0;32m'
+STATUS_COLOR='\e[0;32m'
+ERROR_COLOR='\e[0;31m'
 NC='\e[0m'
 
-folder_mongo_root=`sudo find / -name mongod | sed 's/.\{11\}$//'`
+echo_Status () {
+	echo -e "${STATUS_COLOR}${1}${NC}"
+}
 
-##### STARTING historicalTweets.py
-echo -e "${COLOR}Checking for running instance of historicalTweets.py${NC}"
+echo_Error () {
+	echo -e "${ERROR_COLOR}${1}${NC}"
+}
+
+######INITIALIZATION CODE = Derive/validate paths.
+folder_mongo_root=`sudo which mongod`
+if [ "${folder_mongo_root}" = "" ] #Check mongod was found
+then
+	echo_Error"Could not find location of mongod"
+	exit 1
+else
+	folder_mongo_root=${folder_mongo_root%\/mongod}
+fi
+
+######INITIALIZATION CODE ends
+
+##### STOPPING historicalTweets.py
+echo_Status "Checking for running instance of historicalTweets.py"
 historicalTweets_running=`pgrep -f historicalTweets.py | wc -l`
 if [[ $historicalTweets_running == 0 ]]
-then  	echo -e "${COLOR}historicalTweets.py is not running${NC}"
-	echo -e "${COLOR}Proceeding with execution...${NC}"
-else	echo -e "${COLOR}Running instance of historicalTweets.py detected.${NC}"
-	echo -e "${COLOR}Killing existing instance...${NC}"
+then  	echo_Status "historicalTweets.py is not running"
+	echo_Status "Proceeding with execution..."
+else	echo_Status "Running instance of historicalTweets.py detected."
+	echo_Status "Killing existing instance..."
 	pgrep -f historicalTweets.py | xargs kill
 fi
-echo -e "${COLOR}Historical Tweets instance killed${NC}"
-
+echo_Status "Historical Tweets instance killed"
+##### STOPPING historicalTweets.py ends
 
 ##### STOPPING crisisServer.py
-echo -e "${COLOR}Checking for running instance of crisisSever${NC}"
+echo_Status "Checking for running instance of crisisSever"
 crisisServer_running=`pgrep -f crisisServer.py | wc -l`
 if [[ $crisisServer_running == 0 ]]
-then  	echo -e "${COLOR}crisisServer is not running${NC}"
-	echo -e "${COLOR}Proceeding with execution...${NC}"
-else	echo -e "${COLOR}Running instance of crisisServer detected.${NC}"
-	echo -e "${COLOR}Killing existing instance...${NC}"
+then  	echo_Status "crisisServer is not running"
+	echo_Status "Proceeding with execution..."
+else	echo_Status "Running instance of crisisServer detected."
+	echo_Status "Killing existing instance..."
 	pgrep -f crisisServer.py | xargs kill
 fi
-echo -e "${COLOR}Crisis Server instance killed.${NC}"
-
+echo -e "${COLOR}Crisis Server instance killed."
+##### STOPPING crisisServer.py ends
 
 ###### STOP MONGOD
-echo -e "${COLOR}Checking for running instance of Mongo DB server.${NC}"
+echo_Status "Checking for running instance of Mongo DB server."
 mongod_running=`pgrep -f mongod | wc -l`
 if [[ $mongod_running == 0 ]]
-then  	echo -e "${COLOR}Mongo DB server is not running${NC}"
-	echo -e "${COLOR}Proceeding with execution...${NC}"
-else	echo -e "${COLOR}Running instance of Mongo DB server detected.${NC}"
-	sudo ${folder_mongo_root}/bin/mongod --shutdown
-	echo -e "${COLOR}Stopped Mongo DB server${NC}"
+then  	echo_Status "Mongo DB server is not running"
+	echo_Status "Proceeding with execution..."
+else	echo_Status "Running instance of Mongo DB server detected."
+#	sudo ${folder_mongo_root}/bin/mongod --shutdown
+	mongo << EOF
+use admin
+db.shutdownServer()
+exit
+EOF
+	echo_Status "Stopped Mongo DB server"
 fi
+###### STOP MONGOD ends
+
+rm -f nohup.out
